"""The Chronicle of the Ancient Lords, in pages.

One text, cut into fragments a player finds one at a time -- anywhere, in any
order -- and which assemble into the whole book in the menu. The
numbering is the point: a page found on floor two that belongs in the middle
of the book goes into the middle of the book, and the gaps around it are
what is still missing.

Generated by ``tools/make_lore.py`` from ``docs/lore.txt``, and committed.
The game never runs the tool; the pages are here.
"""

from __future__ import annotations

__all__ = ["TITLE", "PAGES", "PAGE_COUNT", "page", "numeral"]

#: What the book is called, in the menu and at the top of every page.
TITLE = 'The Chronicle of the Ancient Lords'

#: Every page, in the order they belong in. The index is the number minus
#: one, and the number is what a player sees -- a page is a *page*, not a
#: token, and it says which one it is.
PAGES: tuple[str, ...] = (
    # I
    'Now it is told in the elder chronicles that, before the kingdoms of men had taken '
    'the shape wherein they are known in these latter days, and before the names of kings '
    'and great lords were written upon the stones of their halls, there were four men who '
    'were accounted the greatest among those who bore the powers of the elements, and '
    'these four were called by the old writers the Ancient Lords.',
    # II
    'Yet let it not be thought that they were gods, for they were no gods, neither were '
    'they worshipped as such, nor did they fashion the earth or command the souls of men, '
    'but they were men, or men of such nature as was near unto mankind, who had come into '
    'possession of powers greater than any man before them had been known to bear.',
    # III
    'The first of these was Fireking, Lord of Fire, whose flame was said to burn hotter '
    'than the heart of the mountain; the second was Yeti, Lord of Ice, whose strength was '
    'as the winter and whose patience was greater than the passing of years; the third '
    'was Gaia, Lord of Earth, who held within himself the weight and strength of the '
    'living ground; and the fourth was Shocker, Lord of Lightning, swift and terrible, '
    'whose coming was like the wrath of the heavens.',
    # IV
    'And these four stood together in those days against a man whose name is yet '
    'remembered, though many of the deeds that he wrought have been hidden from the '
    'knowledge of men, and his name was Neverdead.',
    # V
    'Now Neverdead had once been a necromancer of great ambition, and it is said that he '
    'sought knowledge which no mortal ought to seek, for he desired not merely to raise '
    'the dead and command those who had passed beyond the grave, but sought rather to '
    'bring forth into the world that which was darkest and most hidden, believing that if '
    'he might but master the darkness at its source, then no power of life, nor death, '
    'nor nature itself, could stand against him.',
    # VI
    'And because of this purpose there arose many wars between Neverdead and the four '
    'Ancient Lords, and many times was Neverdead defeated and cast down, yet always did '
    'he return, for he possessed a patience beyond that of ordinary men, and the years '
    'which passed away from others were to him as but moments.',
    # VII
    'Thus the four Lords came at length to understand that there was no simple strength '
    'by which Neverdead might be destroyed, for fire might consume his servants, and ice '
    'might imprison them, and earth might swallow them, and lightning might tear them '
    'asunder, yet Neverdead himself would ever find some road by which to return.',
    # VIII
    'And there came upon the Lords a grievous knowledge, which they would gladly have '
    'refused had there been another way, namely that as fire must sometimes be answered '
    'with fire, so must darkness be answered by darkness, and that which could not be '
    'overcome by the light might perhaps be overcome by a shadow of equal depth. It was '
    'then that Fireking chose to give himself.',
    # IX
    'Of the last conversation between Fireking and the other Lords there remaineth no '
    'true account, for none who heard it wrote of it, and those who might have known the '
    'words carried them with them to the grave. Yet it is certain that Fireking went '
    'forth alone upon a great field which had already been ruined by war, and there did '
    'he meet Neverdead, and there did he unleash the whole of his power.',
    # X
    'His fire grew so fierce that the stones beneath his feet were melted, and the '
    'heavens above him were made red by the burning, until at the last the flame consumed '
    'not only his enemy but the Lord himself, so that his flesh became ash and his bones '
    'were no more, and all that remained of Fireking was a great black dust which the '
    'wind carried over the earth.',
    # XI
    'Now it happened that this took place at the hour of sunset, when the light of the '
    'sun is long and red upon the ground, and the black ash of Fireking was scattered far '
    'across the plain until the whole land seemed divided between the last light of day '
    'and the coming darkness. Then, as the old chroniclers tell it, something strange '
    'befell, for the ash ceased to move with the wind and gathered where the light grew '
    'weakest, and there it became as a shadow, though no man stood before it to cast such '
    'a thing.',
    # XII
    'And from that shadow there arose a man. His name was Noxx. And Noxx was the Lord of '
    'Darkness. Yet Noxx was not Fireking returned from death, though within him there '
    'remained fragments of the one who had been Fireking, and memories would sometimes '
    'come upon him without warning, as dreams come upon a man in sleep.',
    # XIII
    'At one time he would remember the warmth of a great flame, and at another the face '
    'of a companion whose name he could no longer recall, and at another he would hear a '
    'voice calling him from far away, and then all would be gone again, leaving him '
    'uncertain whether the memory had truly belonged to him or to another. Thus was Noxx '
    'a new beginning, though he carried within him the remains of an older life.',
    # XIV
    'But there was another thing born with him, and this thing was not Fireking, nor was '
    'it any power that had belonged to him before, but rather the darkness itself, which '
    'had taken form and will and had given unto itself the name Atritas. Now Atritas was '
    'bound to Noxx, and Noxx to Atritas, and from that day forth there began within Noxx '
    'a battle which no other man could behold. For Atritas desired the mastery of the '
    'body, while Noxx desired to remain himself, and neither could wholly destroy the '
    'other.',
    # XV
    'At times Atritas would appear to Noxx as a voice, and at other times as a figure, '
    "and often he took the shape of Noxx's own shadow, though this was a strange thing, "
    'for Noxx himself cast no shadow as other men do. The thing which followed him was '
    'something altogether different.',
    # XVI
    'It lay upon the ground like deep black water, and whosoever looked upon it had the '
    'dreadful sense that it possessed no bottom, for there was neither reflection nor '
    'light within it, and the longer a man gazed into it, the more did he feel as though '
    'he were sinking into some place beneath the world where no light had ever been and '
    'where no living thing could breathe. It was not merely darkness, but a darkness '
    'which seemed to have depth, and those few who came too near it were wise to turn '
    'their eyes away.',
    # XVII
    'Yet Noxx learned in time to command that darkness, and through it he became stronger '
    'than any Lord who had stood before him. But this strength was not given freely, for '
    'every victory over Atritas made Atritas stronger, and every time Noxx drove him back '
    'into the depths of his own being, the thing returned again, waiting patiently for '
    'another hour.',
    # XVIII
    'Thus the battle between them became without end, and there are some among the oldest '
    'keepers of the chronicles who believe that Noxx and Atritas shall remain bound '
    'together until the end of all things, for neither can live wholly without the other. '
    'But whilst these things came to pass with Noxx, the fire of Fireking had not wholly '
    'vanished from the world. For the fire sought a new vessel, and it found Gaia.',
    # XIX
    'At first the change was small, and none could perceive it, but after a time the '
    'earth beneath Gaia began to burn, and stones cracked beneath his feet, and mountains '
    'stirred, and the ground itself seemed to groan as though something within it desired '
    'to break free. The fire of Fireking had entered into the Lord of Earth, and the '
    'strength of the earth and the fury of the flame became joined together. From this '
    'union there came another Lord, whose name was Inferno.',
    # XX
    'Yet Inferno was not Fireking, and none who knew the old Lord would have mistaken one '
    'for the other, for Fireking had possessed mastery over his flame, whilst Inferno '
    'seemed driven by it. He was restless and wrathful, and though he possessed the '
    'strength of the earth within him, he had not inherited the peace which Gaia had once '
    'known. The fire burned in him without rest, and the ground itself answered to his '
    'anger.',
    # XXI
    'And from that time there grew a saying among those who knew the old tales, namely '
    'that the Earth would one day seek another vessel, for that which had been taken from '
    'Gaia could not remain forever in the form it had found. Whether this is true none '
    'can say, for the oldest books speak only in riddles upon this matter, and some have '
    'claimed that the Earth hath already found another host, though that person knoweth '
    'nothing of what lies sleeping within him. Neither were Fireking and Gaia the only '
    'Lords who passed from the world.',
    # XXII
    'For there are ancient books, older than the kingdoms which now claim dominion over '
    'the lands, wherein there is mention of other Lords whose names have been lost. One '
    'is said to have been Lord of Plants, whose strength was found in root and thorn and '
    'leaf, whilst others are described only as Lords of powers made by the hands of men, '
    'which some writings call the man-made elements. Yet the names of these beings are '
    'nowhere preserved in full, and in many places the pages upon which they were written '
    'have been torn away.',
    # XXIII
    'There are stones bearing marks which have been struck from their surface, and '
    'statues whose faces have been broken, and books in which whole passages have been '
    'removed so carefully that it is plain the forgetting was not the work of time alone. '
    'Why such things were done no man living can tell. There is also written of another '
    'shadow, though it was unlike the shadow of Atritas, for whereas Atritas was like '
    'deep black water, this other shadow had no depth at all.',
    # XXIV
    'It possessed neither height nor breadth as a man would understand such things, and '
    'those who described it said that it seemed like an object from another place, cut '
    'loose from whatever world had made it and left upon this one, as though it waited '
    'for a hand to take it up. Yet the account ends there, and the pages following are '
    'empty. Then came the disappearance of Shocker. Now Shocker had always been the '
    'swiftest and most restless of the Ancient Lords, and he was ever drawn toward things '
    'which other men feared to approach.',
    # XXV
    'Thus it came to pass that he discovered a great machine beneath the earth, so vast '
    'that its iron workings were greater than houses, and its purpose was unknown even to '
    'those who possessed knowledge of such things. None knew who had made it, nor for '
    'what purpose it had been fashioned, and there are some who say that it was older '
    'than the four Lords themselves. Shocker entered the machine.',
    # XXVI
    'Lightning ran across its walls, and the heavens above it were filled with thunder, '
    'but after a single great flash the machine vanished, and with it went Shocker. Never '
    'again was he seen. Some said that he had perished, others that he had been '
    'imprisoned, and still others that the machine had not destroyed him at all but had '
    'carried him to some place beyond the knowledge of men, where time itself did not '
    'pass as it did in the world.',
    # XXVII
    'Even in these latter days there are those who claim that on certain nights, when the '
    'sky is clear and no storm is near, they have heard a single great thunderclap roll '
    'across the land, though no lightning followed it. But whether this be truth or '
    'fancy, none can tell. Of the four Ancient Lords, only Yeti remained. He was unlike '
    'the others, for where Fireking was fierce, Gaia steadfast and Shocker restless, Yeti '
    'possessed a patience which seemed almost without limit.',
    # XXVIII
    'The passing of years troubled him little, and the things which would have seemed an '
    'age to another man passed before him as a long winter. He watched kingdoms rise and '
    'fall, saw men whom he had known as children become old and die, and kept within his '
    'memory the things which all others had forgotten.',
    # XXIX
    'His palace of ice stood far in the north, beyond mountains whose peaks were never '
    'free of snow, and within that palace were kept many of the oldest secrets of the '
    'Lords. Books were hidden there which no living man could properly read, and weapons '
    'rested beneath the ice which none dared touch, and there the Ancient Lords had once '
    'gathered when matters too dangerous to be spoken of before ordinary men required '
    'counsel.',
    # XXX
    'The palace had been a place of meeting, a place of refuge, and at times a place '
    'where enemies had sat together and made plans against greater enemies. But as the '
    'years passed and the old Lords vanished, the great hall grew silent. Fireking was '
    'gone. Gaia was gone. Shocker had vanished. Noxx had become a creature of shadow and '
    'was wandering beyond the sight of men. And Yeti remained. He alone carried the '
    'memory of what the world had once been.',
    # XXXI
    'Then, after many years had passed and the names of Fireking and Gaia had become '
    'little more than old tales told by men who no longer believed them, there came to '
    'the Ice Palace a new Lord. His name was Walkyrion.',
    # XXXII
    'Of his coming there are few accounts, and none say from whence he came, nor what '
    'power was hidden within him, but all agree that there was something in his bearing '
    'which marked him as one who had been chosen for a greater purpose, though he himself '
    'had not yet discovered the full measure of his strength. He wore garments of gold, '
    'and upon his person there was a splendour unlike that of kings, for it seemed less '
    'the splendour of wealth than the promise of a power not yet awakened.',
    # XXXIII
    'Thus did Walkyrion enter the Ice Palace and stand before Yeti, who had watched the '
    'passing of centuries from his frozen hall. For a long while neither spoke. Then '
    'Walkyrion drew his sword, and instead of raising it against Yeti, he cast it down '
    'upon the floor between them.',
    # XXXIV
    'The blade struck the ancient stone with a great sound which rang through the hall '
    'and passed into the walls of ice, and the sound was so mighty that the palace itself '
    'seemed to answer, for cracks appeared upon the frozen pillars and small shards fell '
    'from the ceiling, and Yeti, who had seen many things in his long life, raised his '
    'eyes at once. For no sword had ever before made the walls of his palace tremble.',
    # XXXV
    'Then Yeti understood that the coming of Walkyrion was not the arrival of another '
    'wanderer seeking shelter, but the beginning of something which had been waiting for '
    'many years to come to pass. For Walkyrion had come not for glory, nor for gold, nor '
    'for dominion over men, but to stand against Neverdead. And when at last he spoke, '
    'his words were few, but they carried farther through the hall than the sound of his '
    'sword. He said that Neverdead yet lived. And at those words Yeti knew that the long '
    'silence had ended.',
    # XXXVI
    'For beneath the ancient ice, something stirred which had lain sleeping since the '
    'days when Fireking still walked the earth, and far beyond the northern mountains, '
    'where no flame burned and no living man stood near, Noxx opened his eyes. His shadow '
    'moved upon the ground. The blackness spread like still water. And from within it '
    'there came the eyes of Atritas, watching, waiting, as he had watched and waited for '
    'all the years that had passed. For Atritas had never been gone. Nor had Neverdead '
    'forgotten.',
    # XXXVII
    'The Ancient Lords had fallen, one by one, and those who came after them had yet to '
    'discover what powers lay within their blood and their souls, but the old war had not '
    'ended with the passing of the old age. It had merely gone into silence. And now the '
    'silence was broken.',
)

#: How many there are to find.
PAGE_COUNT = len(PAGES)


def page(number: int) -> str | None:
    """The text of one page, or ``None`` for a page that does not exist."""
    if 1 <= number <= PAGE_COUNT:
        return PAGES[number - 1]
    return None


def numeral(number: int) -> str:
    """A page number the way a chronicle writes one."""
    out = []
    for value, letters in ROMAN:
        while number >= value:
            out.append(letters)
            number -= value
    return "".join(out)


ROMAN = (
    (1000, "M"), (900, "CM"), (500, "D"), (400, "CD"),
    (100, "C"), (90, "XC"), (50, "L"), (40, "XL"),
    (10, "X"), (9, "IX"), (5, "V"), (4, "IV"), (1, "I"),
)
