#!/usr/bin/env python3
"""Cut the chronicle into pages.

The lore is one long text and the game needs it in fragments: pages a player
finds one at a time, anywhere, in any order, and which assemble into the whole
book on a shelf in the menu. So the cutting is a program -- the same idea as
``make_art.py`` and ``make_font.py``, and for the same reason: a split that can
be re-run is a split that can be re-tuned, and the alternative is editing
thirty-seven strings by hand whenever a sentence moves.

Pages break at paragraph ends wherever one is close enough, and inside a long
paragraph when it is not. That is deliberate rather than tidy: the pages are
meant to read like pages torn out of a book, and a book whose every page ends
exactly where a thought ends is not a book anybody tore.

    python3 tools/make_lore.py            # from docs/lore.txt
    python3 tools/make_lore.py --target 60

The generated module is committed. The game never runs this.
"""

from __future__ import annotations

import argparse
import re
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "docs" / "lore.txt"
OUT = ROOT / "src" / "neverdeads_revenge" / "game" / "lore.py"

#: Words a page wants. A page is read in a moment, standing in a corridor with
#: something coming -- which is where every page in this game is read.
TARGET_WORDS = 75

#: How far past the target a page may run before it is cut at the next
#: paragraph rather than the next sentence. The slack is what lets a page end
#: where the *writing* ends instead of where the arithmetic does.
SLACK = 1.3

ROMAN = (
    (1000, "M"), (900, "CM"), (500, "D"), (400, "CD"),
    (100, "C"), (90, "XC"), (50, "L"), (40, "XL"),
    (10, "X"), (9, "IX"), (5, "V"), (4, "IV"), (1, "I"),
)


def numeral(number: int) -> str:
    """A page number the way a chronicle writes one."""
    out = []
    for value, letters in ROMAN:
        while number >= value:
            out.append(letters)
            number -= value
    return "".join(out)


def _sentences(paragraph: str) -> list[str]:
    return [part.strip() for part in re.split(r"(?<=[.!?])\s+", paragraph) if part.strip()]


def cut(text: str, target: int = TARGET_WORDS) -> tuple[str, list[str]]:
    """Split the chronicle into pages. Returns the title and the pages."""
    title, body = text.strip().split("\n", 1)
    paragraphs = [p.strip() for p in body.split("\n\n") if p.strip()]

    pages: list[str] = []
    current: list[str] = []
    words = 0
    for paragraph in paragraphs:
        # A paragraph longer than a page is cut by sentence; a shorter one is
        # left whole, because a paragraph is already a thought.
        chunks = (
            _sentences(paragraph)
            if len(paragraph.split()) > target
            else [paragraph]
        )
        for chunk in chunks:
            size = len(chunk.split())
            if current and words + size > target * SLACK:
                pages.append(" ".join(current))
                current, words = [], 0
            current.append(chunk)
            words += size
    if current:
        pages.append(" ".join(current))
    return title.strip(), pages


def write(title: str, pages: list[str]) -> Path:
    lines = [
        '"""The Chronicle of the Ancient Lords, in pages.',
        "",
        "One text, cut into fragments a player finds one at a time -- anywhere, in any",
        "order -- and which assemble into the whole book on a shelf in the menu. The",
        "numbering is the point: a page found on floor two that belongs in the middle",
        "of the book goes into the middle of the book, and the gaps around it are",
        "what is still missing.",
        "",
        "Generated by ``tools/make_lore.py`` from ``docs/lore.txt``, and committed.",
        "The game never runs the tool; the pages are here.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        '__all__ = ["TITLE", "PAGES", "PAGE_COUNT", "page", "numeral"]',
        "",
        f"#: What the book is called, on the shelf and at the top of every page.",
        f"TITLE = {title!r}",
        "",
        "#: Every page, in the order they belong in. The index is the number minus",
        "#: one, and the number is what a player sees -- a page is a *page*, not a",
        "#: token, and it says which one it is.",
        "PAGES: tuple[str, ...] = (",
    ]
    for index, body in enumerate(pages, start=1):
        lines.append(f"    # {numeral(index)}")
        # Wrapped into several literals for the sake of the diff, with the space
        # *inside* each one: adjacent string literals concatenate with nothing
        # between them, so a page written as separate pieces arrives as
        # "Lord ofDarkness". Which it did, and which is what the check below
        # exists to catch.
        pieces = textwrap.wrap(body, width=84, break_long_words=False)
        assert " ".join(pieces) == body, f"page {index} lost a space in the wrap"
        for position, piece in enumerate(pieces):
            trailing = " " if position < len(pieces) - 1 else ""
            lines.append(f"    {piece + trailing!r}")
        lines[-1] = lines[-1] + ","
    lines += [
        ")",
        "",
        "#: How many there are to find.",
        "PAGE_COUNT = len(PAGES)",
        "",
        "",
        "def page(number: int) -> str | None:",
        '    """The text of one page, or ``None`` for a page that does not exist."""',
        "    if 1 <= number <= PAGE_COUNT:",
        "        return PAGES[number - 1]",
        "    return None",
        "",
        "",
        "def numeral(number: int) -> str:",
        '    """A page number the way a chronicle writes one."""',
        "    out = []",
        "    for value, letters in ROMAN:",
        "        while number >= value:",
        "            out.append(letters)",
        "            number -= value",
        '    return "".join(out)',
        "",
        "",
        "ROMAN = (",
        '    (1000, "M"), (900, "CM"), (500, "D"), (400, "CD"),',
        '    (100, "C"), (90, "XC"), (50, "L"), (40, "XL"),',
        '    (10, "X"), (9, "IX"), (5, "V"), (4, "IV"), (1, "I"),',
        ")",
        "",
    ]
    OUT.write_text("\n".join(lines))
    return OUT


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=SOURCE)
    parser.add_argument("--target", type=int, default=TARGET_WORDS)
    args = parser.parse_args()

    title, pages = cut(args.source.read_text(), args.target)
    path = write(title, pages)
    sizes = [len(p.split()) for p in pages]
    print(
        f"wrote {path.name}: {len(pages)} pages, "
        f"{min(sizes)}-{max(sizes)} words each"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
