"""Sound effects.

Two things had to be true for this to be worth having.

The first is that it is never *required*. A terminal game has no business
assuming it can make a noise, so this finds a player if there is one and does
nothing at all if there is not -- no error, no delay, no missing feature. The
sounds themselves are generated by ``tools/make_sounds.py`` and ship inside the
package.

The second is that it is never *late*. Spawning a player per sound measured at
190ms on the machine this was written on, of which the sound itself was fifty:
a fight is faster than that, so the first blow produced nothing and the next four
arrived in a heap. The fix is to keep one player open and write raw samples into
it -- ten microseconds a sound instead of a hundred and ninety milliseconds --
and to drop a sound whose moment has passed rather than queueing it behind the
one playing.

Turn it off with ``NEVERDEADS_REVENGE_MUTE=1``, with ``--no-sound``, or from the
pause menu, which remembers.
"""

from __future__ import annotations

import os
import queue
import shutil
import subprocess
import sys
import threading
import time
import wave
from dataclasses import dataclass
from pathlib import Path

from ..game.state import LogKind

__all__ = [
    "Sfx",
    "Player",
    "SOUNDS_DIR",
    "RATE",
    "MUTE_ENV",
    "BY_KIND",
    "LOUDNESS",
    "URGENT",
    "sound_for_kind",
    "loudest_kind",
]

#: Where the generated sounds live. Inside the package rather than in
#: ``assets/``: the icon is a desktop-file asset that only the installer reads,
#: and these are read at runtime, so they have to travel with the code.
SOUNDS_DIR = Path(__file__).resolve().parent.parent / "sounds"

#: The rate the sounds are generated at. ``tools/make_sounds.py`` writes it into
#: every file and the tests check they agree; a stream player needs it as a
#: number on the command line.
RATE = 11025

#: Set this to anything to start with the sound off. It can only ever mute --
#: a setting that says "on" cannot override it, because the one caller that
#: matters is the test suite.
MUTE_ENV = "NEVERDEADS_REVENGE_MUTE"

#: Set this to a path and every sound decision is appended to it.
#:
#: For the case where the sound is wrong and nobody can hear it from where the
#: code was written. The game cannot know whether a note came out of the
#: speaker, but it can say exactly what it asked for, when, and how far behind
#: the device already was -- and that is the difference between a bug and a
#: guess.
DEBUG_ENV = "NEVERDEADS_REVENGE_SOUND_LOG"

#: How far behind the device may fall before a sound is dropped rather than
#: queued.
#:
#: The old rule dropped a sound the moment the device was busy with any of the
#: previous one, which is why a kill -- a hundred and ninety milliseconds --
#: swallowed the blow that landed on top of it. A quarter of a second of backlog
#: is inaudible and is not a reason to throw a sound away; more than that is.
MAX_BACKLOG = 0.25

#: Marks the in-process Windows player, which has no command line.
WINSOUND = "__winsound__"

#: How many failures in a row before the game gives up on sound.
#:
#: One was too few. A single hiccup -- a broken pipe at the wrong moment, a
#: transient error from the audio server -- used to silence the rest of the
#: session, and the player would hear nothing for the rest of the run without
#: being told why. A hiccup is not a broken machine; three in a row is.
GIVE_UP_AFTER = 3

#: Which sound a message gets, by the log's own classification.
#:
#: The log already sorts itself into combat, damage and the rest, so the sound
#: is a second reading of one classification rather than a second place for the
#: rules to be written down. The plainer kinds are silent on purpose: a sound
#: for every line is a sound for none of them.
BY_KIND: dict[LogKind, str] = {
    LogKind.CRIT: "crit",
    LogKind.COMBAT: "hit",
    LogKind.DAMAGE: "hurt",
    LogKind.BAD: "curse",
    LogKind.GOOD: "item",
    LogKind.COIN: "coin",
}

#: Which sound wins when one turn produces several messages.
#:
#: Taking a blow beats landing one, and landing one beats everything quieter. A
#: turn that produces three lines should sound like the worst thing that
#: happened in it, not like all three at once.
LOUDNESS: dict[LogKind, int] = {
    LogKind.DAMAGE: 5,
    LogKind.CRIT: 4,
    LogKind.COMBAT: 3,
    LogKind.BAD: 2,
    LogKind.COIN: 1,
    LogKind.GOOD: 1,
}

#: Sounds that are never dropped, however busy the device is.
#:
#: They are rare and they mean something. A hit sound that arrives late is a hit
#: sound about a moment that has gone; a level arriving late is still the level,
#: and swallowing it because a fight was in progress would be the one case where
#: the fix is worse than the problem.
URGENT: frozenset[str] = frozenset({"level", "death", "victory", "chest", "stairs"})


def sound_for_kind(kind: LogKind) -> str | None:
    """The sound a message of this kind makes, or ``None`` for silence."""
    return BY_KIND.get(kind)


def loudest_kind(kinds) -> LogKind | None:
    """The kind worth making a noise about, out of everything that happened."""
    best = None
    best_score = 0
    for kind in kinds:
        score = LOUDNESS.get(kind, 0)
        if score > best_score:
            best, best_score = kind, score
    return best


@dataclass(frozen=True, slots=True)
class Player:
    """A way to make a noise, and whether it can be kept open.

    ``streams`` is the whole point of the type. A player that reads raw samples
    from standard input can be started once and fed for the rest of the session,
    which is what makes a sound effect land on the blow instead of after it. A
    player that only takes a filename has to be spawned per sound, and is kept
    as the fallback it is.
    """

    command: list[str]
    streams: bool = False


@dataclass(frozen=True, slots=True)
class Clip:
    """One sound, loaded once."""

    path: Path
    frames: bytes
    seconds: float


def _find_player() -> Player | None:
    """A way to play a sound, or ``None``.

    In order of how likely it is to be there, and preferring the ones that can
    be kept open. ``afplay`` is last and does not stream: it takes a filename and
    nothing else, so on a Mac the sound is late -- which is a real cost, and
    still better than being silent.
    """
    if sys.platform == "win32":
        return Player([WINSOUND])

    raw = ["-q", "-t", "raw", "-f", "S16_LE", "-r", str(RATE), "-c", "1", "-"]
    if shutil.which("aplay"):
        return Player(["aplay", *raw], streams=True)

    if shutil.which("ffplay"):
        return Player(
            [
                "ffplay",
                "-nodisp",
                "-autoexit",
                "-loglevel",
                "quiet",
                "-f",
                "s16le",
                "-ar",
                str(RATE),
                "-ac",
                "1",
                "-i",
                "-",
            ],
            streams=True,
        )

    # Neither paplay nor pw-play can be fed raw samples: both hand the argument
    # to libsndfile, which wants a container. They take a filename instead.
    for name in ("pw-play", "paplay", "afplay"):
        if shutil.which(name):
            return Player([name])
    return None


class Sfx:
    """One worker thread, a queue, and a player that stays open.

    Not a subprocess per sound: a turn can produce three messages, three players
    at once is a mess, and a ``Popen`` nobody waits for is a zombie. The queue
    serialises them and the thread reaps them -- and the thread is also where the
    decision to *drop* one is made, because that decision needs to know what the
    device is doing right now and not what it was doing when the sound was
    queued.
    """

    def __init__(self, muted: bool | None = None) -> None:
        # The environment can only ever mute. A setting that says "on" must not
        # be able to override it, or the test suite would make a noise on any
        # machine that happens to have a player installed.
        self._muted = bool(os.environ.get(MUTE_ENV)) or bool(muted)
        self.player = _find_player()
        self._clips: dict[str, Clip | None] = {}
        self._stream: subprocess.Popen | None = None
        #: When the device will be free again. Sounds that arrive before this
        #: are dropped rather than queued, unless they are urgent.
        self._free_at = 0.0
        #: Failures in a row, so a hiccup does not silence the session.
        self._failures = 0
        self._debug = os.environ.get(DEBUG_ENV)
        self._queue: queue.Queue[str | None] = queue.Queue()
        self._thread: threading.Thread | None = None
        if self.player is not None:
            self._thread = threading.Thread(
                target=self._work, name="ndr-sfx", daemon=True
            )
            self._thread.start()
            if not self._muted:
                # Warm the device up now rather than on the first blow. Opening
                # it costs about a hundred and forty milliseconds, and paying
                # that on the first hit of the first fight is paying it exactly
                # where it is most noticeable.
                self._open_stream()

    # -- the outside world ---------------------------------------------------
    @property
    def available(self) -> bool:
        """Whether there is a player at all. False means silence forever."""
        return self.player is not None

    @property
    def muted(self) -> bool:
        return self._muted

    def set_muted(self, muted: bool) -> None:
        """Turn the sound off or on again, from the pause menu."""
        self._muted = muted
        self._failures = 0
        if not muted:
            # Unmuting after the device was never opened still needs opening.
            self._open_stream()

    def toggle(self) -> bool:
        """Flip the mute and report the new state."""
        self.set_muted(not self._muted)
        return self._muted

    def play(self, name: str) -> None:
        """Queue a sound. Returns immediately, always."""
        if self._muted or self._thread is None:
            return
        self._queue.put(name)

    def close(self) -> None:
        """Stop the worker and let go of the device."""
        if self._thread is not None:
            self._queue.put(None)
        self._close_stream()

    # -- the worker ----------------------------------------------------------
    def _work(self) -> None:
        while True:
            name = self._queue.get()
            try:
                if name is None:
                    return
                self._play_now(name)
            finally:
                self._queue.task_done()

    def _play_now(self, name: str) -> None:
        clip = self._clip(name)
        if clip is None:
            return

        now = time.monotonic()
        backlog = self._free_at - now
        if backlog > MAX_BACKLOG and name not in URGENT:
            # Genuinely swamped, and its moment has passed. A blow that sounds
            # three blows late is worse than one that does not sound at all --
            # but a blow that sounds a fifth of a second late is not, which is
            # why the threshold is a quarter of a second rather than zero.
            self._note(
                f"DROP {name} ({clip.seconds * 1000:.0f}ms) "
                f"backlog={max(0.0, backlog) * 1000:.0f}ms"
            )
            return

        # Queued behind whatever is playing, not on top of it.
        self._free_at = max(now, self._free_at) + clip.seconds
        self._note(
            f"PLAY {name} ({clip.seconds * 1000:.0f}ms) "
            f"backlog={max(0.0, backlog) * 1000:.0f}ms"
        )
        self._emit(clip)

    def _note(self, line: str) -> None:
        """Write one line to the diagnostic log, if there is one.

        Only ever written from the worker thread, so it needs no lock -- and a
        log that cannot be written is not worth failing over.
        """
        if not self._debug:
            return
        try:
            with open(self._debug, "a", encoding="utf-8") as handle:
                handle.write(f"{time.monotonic():.3f} {line}\n")
        except OSError:
            self._debug = None

    def _emit(self, clip: Clip) -> None:
        if self.player is not None and self.player.streams:
            self._stream_out(clip)
        else:
            self._spawn(clip)

    def _stream_out(self, clip: Clip) -> None:
        process = self._stream
        if process is None or process.poll() is not None:
            self._open_stream()
            process = self._stream
        if process is None or process.stdin is None:
            self._spawn(clip)
            return

        try:
            process.stdin.write(clip.frames)
            process.stdin.flush()
            self._failures = 0
        except OSError:
            # The device went away underneath us. Fall back to spawning, and let
            # the fallback be as late as it has to be -- late is much better
            # than silent.
            self._stream = None
            self._failures += 1
            self._spawn(clip)

    def _open_stream(self) -> None:
        if self.player is None or not self.player.streams:
            return
        try:
            self._stream = subprocess.Popen(
                self.player.command,
                stdin=subprocess.PIPE,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
            self._failures = 0
        except OSError:
            self._stream = None
            self._failures += 1

    def _close_stream(self) -> None:
        process = self._stream
        self._stream = None
        if process is None:
            return
        try:
            if process.stdin is not None:
                process.stdin.close()
            process.wait(timeout=2)
        except (OSError, subprocess.TimeoutExpired):
            process.kill()

    def _spawn(self, clip: Clip) -> None:
        """Play one sound by starting a player for it. The slow path."""
        try:
            if self.player is not None and self.player.command == [WINSOUND]:
                import winsound

                winsound.PlaySound(str(clip.path), winsound.SND_FILENAME)
                self._failures = 0
                return

            assert self.player is not None
            result = subprocess.run(
                [*self.player.command, str(clip.path)],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                check=False,
            )
            # A player that exits non-zero did not play anything, and
            # ``check=False`` would otherwise call that a success.
            if result.returncode != 0:
                self._count_failure()
            else:
                self._failures = 0
        except Exception:
            self._count_failure()

    def _count_failure(self) -> None:
        """Count a failure, and go quiet only if they keep coming.

        A sound is never worth a crash, and a hiccup is not a broken machine.
        The old version muted the whole session on the first exception, which is
        why the sound used to stop and never come back.
        """
        self._failures += 1
        if self._failures >= GIVE_UP_AFTER:
            self._muted = True

    # -- the sounds ----------------------------------------------------------
    def _clip(self, name: str) -> Clip | None:
        """Load a sound once. ``None`` for one that does not exist."""
        if name in self._clips:
            return self._clips[name]

        path = SOUNDS_DIR / f"{name}.wav"
        clip: Clip | None = None
        try:
            with wave.open(str(path), "rb") as handle:
                frames = handle.readframes(handle.getnframes())
                seconds = handle.getnframes() / handle.getframerate()
            clip = Clip(path=path, frames=frames, seconds=seconds)
        except (OSError, wave.Error):
            clip = None

        self._clips[name] = clip
        return clip
