"""Sound effects.

Two things had to be true for this to be worth having.

The first is that it is never *required*. A terminal game has no business
assuming it can make a noise, so this finds a device if there is one and does
nothing at all if there is not -- no error, no delay, no missing feature. The
sounds themselves are generated by ``tools/make_sounds.py`` and ship inside the
package.

The second is that it is never *late* -- and that is what the last two attempts
got wrong. Spawning a player per sound measured at 190ms and produced nothing at
all on the first blow of the first fight. One persistent ``aplay`` reading raw
samples from a pipe fixed the *spawn* cost and made it worse: the code scheduled
by its own clock and dropped by its own estimate of how far behind the device
was, and neither was measured. The device buffers hundreds of milliseconds and
the code never learns that, so half of a fight lands in the wrong order or does
not land at all -- thirteen sounds in a third of a second, and seven of them
dropped, which is exactly the erratic noise this used to be.

So the player is a library that owns its own audio thread and *asks* the code for
what to play: a callback stream, one ring buffer, and the one piece of state the
game was guessing at -- where the device is -- read straight off that buffer. A
sound is inserted behind whatever the device has not played yet, so the order is
the order they were queued in, and the drop decision is a comparison between two
measured numbers rather than a guess.

Turn it off with ``NEVERDEADS_REVENGE_MUTE=1``, with ``--no-sound``, or from the
pause menu, which remembers.

The library is ``miniaudio``. It is imported lazily, because a machine without it
-- or a build that shipped without -- is a game that is silent, not a game that
does not start.
"""

from __future__ import annotations

import os
import queue
import threading
import time
import wave
from array import array
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from ..game.state import LogKind

__all__ = [
    "Sfx",
    "SOUNDS_DIR",
    "RATE",
    "MUTE_ENV",
    "DEBUG_ENV",
    "MAX_BACKLOG",
    "GIVE_UP_AFTER",
    "URGENT",
    "BY_KIND",
    "LOUDNESS",
    "sound_for_kind",
    "loudest_kind",
]

#: Where the generated sounds live. Inside the package rather than in
#: ``assets/``: the icon is a desktop-file asset that only the installer reads,
#: and these are read at runtime, so they have to travel with the code.
SOUNDS_DIR = Path(__file__).resolve().parent.parent / "sounds"

#: The rate the sounds are generated at. ``tools/make_sounds.py`` writes it into
#: every file and the tests check they agree, and the device is opened at the
#: same rate, because a rate mismatch is a slow high-pitched version of the
#: whole soundtrack rather than an error anybody would find.
RATE = 11025

#: Set this to anything to start with the sound off. It can only ever mute --
#: a setting that says "on" cannot override it, because the one caller that
#: matters is the test suite.
MUTE_ENV = "NEVERDEADS_REVENGE_MUTE"

#: Set this to a path and every sound decision is appended to it.
#:
#: For the case where the sound is wrong and nobody can hear it from where the
#: code was written. The game cannot know whether a note came out of the
#: speaker, but it can say exactly what it asked for, when, and how far behind
#: the device already was -- and that is the difference between a bug and a
#: guess.
DEBUG_ENV = "NEVERDEADS_REVENGE_SOUND_LOG"

#: How far behind the device a sound may land before it is dropped rather than
#: queued.
#:
#: Measured, not guessed: it is the volume of the mixing buffer the device has
#: not played yet, in seconds. And with mixing it is a *net* rather than a
#: policy: two sounds in one turn play on top of each other, so the buffer's
#: length is bounded by the longest clip in the game (``death.wav``, 640ms) and
#: 800ms is headroom over a case that should not be reachable. It exists so
#: that a bug in the mixer cannot turn into a fight that is three seconds
#: behind itself.
MAX_BACKLOG = 0.80

#: How many failures in a row before the game gives up on sound.
#:
#: One was too few. A single hiccup -- a transient error from the audio server,
#: a device that cannot be opened -- used to silence the rest of the session, and
#: the player would hear nothing for the rest of the run without being told why.
#: A hiccup is not a broken machine; three in a row is.
GIVE_UP_AFTER = 3

#: Which sound a message gets, by the log's own classification.
#:
#: The log already sorts itself into combat, damage and the rest, so the sound
#: is a second reading of one classification rather than a second place for the
#: rules to be written down. The plainer kinds are silent on purpose: a sound
#: for every line is a sound for none of them.
BY_KIND: dict[LogKind, str] = {
    LogKind.CRIT: "crit",
    LogKind.COMBAT: "hit",
    LogKind.DAMAGE: "hurt",
    LogKind.BAD: "curse",
    LogKind.GOOD: "item",
    LogKind.COIN: "coin",
}

#: Which sound wins when one turn produces several messages.
#:
#: Taking a blow beats landing one, and landing one beats everything quieter. A
#: turn that produces three lines should sound like the worst thing that
#: happened in it, not like all three at once.
LOUDNESS: dict[LogKind, int] = {
    LogKind.DAMAGE: 5,
    LogKind.CRIT: 4,
    LogKind.COMBAT: 3,
    LogKind.BAD: 2,
    LogKind.COIN: 1,
    LogKind.GOOD: 1,
}

#: Sounds that are never dropped, however busy the device is.
#:
#: They are rare and they mean something. A hit sound that arrives late is a hit
#: sound about a moment that has gone; a level arriving late is still the level,
#: and swallowing it because a fight was in progress would be the one case where
#: the fix is worse than the problem.
URGENT: frozenset[str] = frozenset({"level", "death", "victory", "chest", "stairs"})


def sound_for_kind(kind: LogKind) -> str | None:
    """The sound a message of this kind makes, or ``None`` for silence."""
    return BY_KIND.get(kind)


def loudest_kind(kinds) -> LogKind | None:
    """The kind worth making a noise about, out of everything that happened."""
    best = None
    best_score = 0
    for kind in kinds:
        score = LOUDNESS.get(kind, 0)
        if score > best_score:
            best, best_score = kind, score
    return best


@dataclass(frozen=True, slots=True)
class Clip:
    """One sound, loaded once."""

    path: Path
    frames: bytes
    seconds: float


class _Library:
    """The playback library, imported once, for the whole process.

    Imported here rather than at the top of the module so a machine without it
    -- or a build that shipped without -- is a game that is silent rather than a
    game that does not start. ``None`` means exactly that.
    """

    imported: bool = False
    module: Any = None

    @classmethod
    def get(cls):
        if not cls.imported:
            cls.imported = True
            try:
                import miniaudio

                cls.module = miniaudio
            except (ImportError, OSError):
                # No library, or the audio package is present but its device
                # package is broken. Either way: silent, and said so once.
                cls.module = None
        return cls.module


class _Ring:
    """What the device is about to play, as a *mixing* buffer, and the lock.

    The head of this buffer is the device's position: the callback takes from
    the front, a queue adds on top, and everything the old code guessed about
    scheduling is one arithmetic on this one number.

    **A mixer, not a playlist.** The version before this queued sounds
    back-to-back, which is what a pipe to ``aplay`` naturally does -- and a
    fight is faster than the sounds are long, so ten blows a second against
    sounds of a tenth of a second means the buffer ran away and the drop rule
    started deciding what the fight sounded like. That is the erratic noise.
    So a sound is mixed into the buffer *on top of* whatever is already in it,
    at the moment the device is about to play, and the length of the buffer is
    bounded by the longest clip rather than by how many blows landed.
    """

    def __init__(self) -> None:
        self._buf = bytearray()
        self._lock = threading.Lock()

    @property
    def seconds_pending(self) -> float:
        """How many seconds of sound are waiting to be played."""
        with self._lock:
            return len(self._buf) / 2 / RATE

    def pending_frames(self) -> int:
        """How many frames are waiting, for the tests."""
        with self._lock:
            return len(self._buf) // 2

    def drain(self, frame_count: int) -> bytes:
        """Take ``frame_count`` frames off the head: what the device plays next.

        Whatever is missing is silence, and that is not an error -- an empty ring
        is a device with nothing queued, which happens every time the player goes
        quiet for longer than the longest clip.
        """
        wanted = max(0, int(frame_count)) * 2
        with self._lock:
            got = bytes(self._buf[:wanted])
            del self._buf[:wanted]
        return got + b"\x00" * (wanted - len(got))

    def add(self, frames: bytes) -> None:
        """Mix a clip into the buffer, on top of whatever is queued.

        Sample-wise sum with clipping, because that is what a mixer does: two
        blows landing together are one louder sound, not one pushed behind the
        other. The length of the buffer is the longer of the two.
        """
        with self._lock:
            # Padded so the sum is over the whole of the new sound; a shorter
            # buffer is silence at the end, not a truncation.
            if len(self._buf) < len(frames):
                self._buf += b"\x00" * (len(frames) - len(self._buf))
            self._buf = bytearray(self._sum(bytes(self._buf), frames))

    @staticmethod
    def _sum(queued: bytes, arriving: bytes) -> bytes:
        """Add two signed 16-bit little-endian sample streams, clipping."""
        left = array("h")
        left.frombytes(queued)
        right = array("h")
        right.frombytes(arriving)

        short = min(len(left), len(right))
        for index in range(short):
            value = left[index] + right[index]
            # Clipped, the way an audio mixer clips: past the ceiling is the
            # ceiling, not a wrapped-around negative number.
            if value > 32767:
                value = 32767
            elif value < -32768:
                value = -32768
            left[index] = value

        # And the tail of whatever was already queued, which the arriving clip
        # is too short to reach.
        return left.tobytes()

    def clear(self) -> None:
        with self._lock:
            self._buf = bytearray()


class Sfx:
    """One ring buffer, and a device that owns its own audio thread.

    Not a subprocess per sound, and not a pipe to a player whose position the
    code cannot see. ``play`` is a byte append, the device callback is a ring
    drain, and the only number that decides whether a sound is dropped is read
    off the same buffer the sound will be inserted into.
    """

    def __init__(self, muted: bool | None = None) -> None:
        # The environment can only ever mute. A setting that says "on" must not
        # be able to override it, or the test suite would make a noise on any
        # machine that happens to have a player installed.
        self._muted = bool(os.environ.get(MUTE_ENV)) or bool(muted)
        self._clips: dict[str, Clip | None] = {}
        self._ring = _Ring()
        self._device: Any = None
        #: Failures in a row, so a hiccup does not silence the session.
        self._failures = 0
        self._debug = os.environ.get(DEBUG_ENV)
        self._queue: queue.Queue[str | None] = queue.Queue()
        self._thread: threading.Thread | None = self._spawn_worker()

        if not self._muted:
            # Open it now rather than on the first blow: an audio session is
            # created once and reused, and paying for it on the first hit of the
            # first fight is paying it exactly where it shows.
            self._open_stream()

        if self._debug:
            # A header, so the file exists from the moment the game starts. A
            # diagnostic that only appears once something has gone wrong is a
            # diagnostic nobody can tell is switched on.
            lib = _Library.get()
            self._note(
                f"--- sound log: library={'miniaudio' if lib else 'none'} "
                f"device={'open' if self._device else 'closed'} "
                f"muted={self._muted} backlog-limit={MAX_BACKLOG * 1000:.0f}ms ---"
            )

    # -- the outside world ---------------------------------------------------
    @property
    def available(self) -> bool:
        """Whether this machine can make a noise at all. False means silence."""
        return _Library.get() is not None

    @property
    def muted(self) -> bool:
        return self._muted

    def set_muted(self, muted: bool) -> None:
        """Turn the sound off or on again, from the pause menu."""
        self._muted = muted
        self._failures = 0
        if not muted:
            # Unmuting after the device was never opened still needs opening.
            self._open_stream()
        else:
            # And muting does not leave half a fight queued up behind a device
            # that is about to be stopped.
            self._ring.clear()

    def toggle(self) -> bool:
        """Flip the mute and report the new state."""
        self.set_muted(not self._muted)
        return self._muted

    def play(self, name: str) -> None:
        """Queue a sound. Returns immediately, always."""
        if self._muted or self._thread is None:
            return
        self._queue.put(name)

    def close(self) -> None:
        """Stop the worker and let go of the device."""
        if self._thread is not None:
            self._queue.put(None)
        self._close_stream()

    # -- the worker ----------------------------------------------------------
    def _spawn_worker(self) -> threading.Thread | None:
        """The thread that turns queued names into ring bytes.

        It exists for the same reason it always did: the first time a sound is
        played its file is read from disk, and that belongs on a thread rather
        than in the middle of a turn.
        """
        thread = threading.Thread(target=self._work, name="ndr-sfx", daemon=True)
        thread.start()
        return thread

    def _work(self) -> None:
        while True:
            name = self._queue.get()
            try:
                if name is None:
                    return
                self._play_now(name)
            finally:
                self._queue.task_done()

    def _play_now(self, name: str) -> None:
        clip = self._clip(name)
        if clip is None:
            self._note(f"MISSING {name}")
            return

        backlog = self._ring.seconds_pending
        if backlog > MAX_BACKLOG and name not in URGENT:
            # Genuinely swamped, and its moment has passed. A blow that sounds
            # three blows late is worse than one that does not sound at all --
            # but a blow that sounds a quarter of a second late is not, which is
            # what the threshold is. The difference from every earlier version
            # is that "backlog" is read off the ring rather than guessed.
            self._note(
                f"DROP {name} ({clip.seconds * 1000:.0f}ms) "
                f"backlog={backlog * 1000:.0f}ms"
            )
            return

        self._note(
            f"PLAY {name} ({clip.seconds * 1000:.0f}ms) "
            f"backlog={backlog * 1000:.0f}ms"
        )
        self._ring.add(clip.frames)

    def _note(self, line: str) -> None:
        """Write one line to the diagnostic log, if there is one.

        Written from the worker thread and from the device path, so the log is
        appended rather than rewritten -- and a log that cannot be written is
        not worth failing over.
        """
        if not self._debug:
            return
        try:
            with open(self._debug, "a", encoding="utf-8") as handle:
                handle.write(f"{time.monotonic():.3f} {line}\n")
        except OSError:
            self._debug = None

    # -- the device ----------------------------------------------------------
    def _open_stream(self) -> None:
        """Open the device once, in a thread of its own.

        Raises nothing. A machine with no audio is a game that is silent, and
        the fact is worth one line in the sound log if there is one.
        """
        if self._device is not None:
            return

        lib = _Library.get()
        if lib is None:
            self._note("no playback library; staying silent")
            return

        try:
            device = lib.PlaybackDevice(
                output_format=lib.SampleFormat.SIGNED16,
                nchannels=1,
                sample_rate=RATE,
                # Thirty milliseconds. Long enough that the thread is not
                # woken forty times a second by the callback, short enough
                # that a sound queued *now* is heard by the next buffer.
                buffersize_msec=30,
            )
            # Primed before it is handed over: the first call the device makes
            # is a ``send``, and a generator that has never been run would
            # answer it with the *first* ``yield`` rather than a buffer.
            frames = self._frames()
            next(frames)
            device.start(frames)
        except Exception as exc:  # noqa: BLE001 - audio is never worth a crash
            self._failures += 1
            self._note(f"OPEN FAILED {type(exc).__name__}: {exc}")
            self._count_failure()
            return

        self._device = device
        self._failures = 0
        self._note("device open")

    def _frames(self):
        """The callback the device calls for every buffer it plays.

        The device asks for ``frame_count`` frames at a time and this hands it
        what it asks for, off the head of the ring -- which is why the head of
        the ring is the device's position, and everything downstream is
        arithmetic rather than a guess.
        """
        ring = self._ring
        frame_count = yield b""
        while True:
            frame_count = yield ring.drain(frame_count)

    def _close_stream(self) -> None:
        device, self._device = self._device, None
        self._ring.clear()
        if device is None:
            return
        try:
            device.stop()
            device.close()
        except Exception:  # noqa: BLE001 - closing is never worth a crash
            pass

    def _count_failure(self) -> None:
        """Count a failure, and go quiet only if they keep coming.

        A sound is never worth a crash, and a hiccup is not a broken machine.
        The old version muted the whole session on the first exception, which is
        why the sound used to stop and never come back.
        """
        self._failures += 1
        if self._failures >= GIVE_UP_AFTER:
            self._muted = True

    # -- the sounds ----------------------------------------------------------
    def _clip(self, name: str) -> Clip | None:
        """Load a sound once. ``None`` for one that does not exist."""
        if name in self._clips:
            return self._clips[name]

        path = SOUNDS_DIR / f"{name}.wav"
        clip: Clip | None = None
        try:
            with wave.open(str(path), "rb") as handle:
                frames = handle.readframes(handle.getnframes())
                seconds = handle.getnframes() / handle.getframerate()
            clip = Clip(path=path, frames=frames, seconds=seconds)
        except (OSError, wave.Error):
            clip = None

        self._clips[name] = clip
        return clip
