"""Sound effects.

A terminal game has no business assuming it can make a noise. This finds a
player if there is one, plays through a single worker thread, and does nothing
at all if there is no player to be found -- no error, no delay, no missing
feature. The sounds themselves are generated by ``tools/make_sounds.py`` and
ship inside the package.

Turn it off with ``NEVERDEADS_REVENGE_MUTE=1``, or from the pause menu.
"""

from __future__ import annotations

import os
import queue
import shutil
import subprocess
import sys
import threading
from pathlib import Path

from ..game.state import LogKind

__all__ = [
    "Sfx",
    "SOUNDS_DIR",
    "MUTE_ENV",
    "BY_KIND",
    "LOUDNESS",
    "sound_for_kind",
    "loudest_kind",
]

#: Where the generated sounds live. Inside the package rather than in
#: ``assets/``: the icon is a desktop-file asset that only the installer reads,
#: and these are read at runtime, so they have to travel with the code.
SOUNDS_DIR = Path(__file__).resolve().parent.parent / "sounds"

#: Set this to anything to start with the sound off.
MUTE_ENV = "NEVERDEADS_REVENGE_MUTE"

#: Which sound a message gets, by the log's own classification.
#:
#: The log already sorts itself into combat, damage and the rest, so the sound
#: is a second reading of one classification rather than a second place for the
#: rules to be written down. The plainer kinds are silent on purpose: a sound
#: for every line is a sound for none of them.
BY_KIND: dict[LogKind, str] = {
    LogKind.CRIT: "crit",
    LogKind.COMBAT: "hit",
    LogKind.DAMAGE: "hurt",
    LogKind.BAD: "curse",
    LogKind.GOOD: "item",
    LogKind.COIN: "coin",
}

#: Which sound wins when one turn produces several messages.
#:
#: Taking a blow beats landing one, and landing one beats everything quieter. A
#: turn that produces three lines should sound like the worst thing that
#: happened in it, not like all three at once.
LOUDNESS: dict[LogKind, int] = {
    LogKind.DAMAGE: 5,
    LogKind.CRIT: 4,
    LogKind.COMBAT: 3,
    LogKind.BAD: 2,
    LogKind.COIN: 1,
    LogKind.GOOD: 1,
}


def sound_for_kind(kind: LogKind) -> str | None:
    """The sound a message of this kind makes, or ``None`` for silence."""
    return BY_KIND.get(kind)


def loudest_kind(kinds) -> LogKind | None:
    """The kind worth making a noise about, out of everything that happened."""
    best = None
    best_score = 0
    for kind in kinds:
        score = LOUDNESS.get(kind, 0)
        if score > best_score:
            best, best_score = kind, score
    return best


def _find_player() -> list[str] | None:
    """A command that plays a WAV file, or ``None``.

    In order of how likely it is to be there and how quietly it does its job.
    ``ffplay`` is last because it wants telling not to open a window, and
    ``winsound`` is not a command at all -- it is the standard library, and it is
    the only one of these that is always present on the platform it belongs to.
    """
    if sys.platform == "win32":
        return [WINSOUND]
    for command in (
        ["paplay"],
        ["aplay", "-q"],
        ["ffplay", "-nodisp", "-autoexit", "-loglevel", "quiet"],
        ["afplay"],
    ):
        if shutil.which(command[0]):
            return command
    return None


#: Marks the in-process Windows player, which has no command line.
WINSOUND = "__winsound__"


class Sfx:
    """One worker thread and a queue.

    Not a subprocess per sound: a turn can produce three messages, three players
    at once is a mess, and a ``Popen`` nobody waits for is a zombie. The queue
    serialises them and the thread reaps them, and a sound that arrives while
    another is playing waits its turn rather than being dropped -- at these
    lengths the wait is milliseconds.
    """

    def __init__(self, enabled: bool | None = None) -> None:
        if enabled is None:
            enabled = not os.environ.get(MUTE_ENV)
        self.player = _find_player()
        self._muted = not enabled or self.player is None
        self._queue: queue.Queue[str | None] = queue.Queue()
        self._thread: threading.Thread | None = None
        if self.player is not None:
            self._thread = threading.Thread(
                target=self._work, name="ndr-sfx", daemon=True
            )
            self._thread.start()

    @property
    def available(self) -> bool:
        """Whether there is a player at all. False means silence forever."""
        return self.player is not None

    @property
    def muted(self) -> bool:
        return self._muted

    def set_muted(self, muted: bool) -> None:
        """Turn the sound off or on again, from the pause menu."""
        self._muted = muted

    def toggle(self) -> bool:
        """Flip the mute and report the new state."""
        self.set_muted(not self._muted)
        return self._muted

    def play(self, name: str) -> None:
        """Queue a sound. Returns immediately, always."""
        if self._muted or self._thread is None:
            return
        self._queue.put(name)

    def close(self) -> None:
        """Ask the worker to stop. It is a daemon, so this is politeness."""
        if self._thread is not None:
            self._queue.put(None)

    def _work(self) -> None:
        while True:
            name = self._queue.get()
            try:
                if name is None:
                    return
                self._play_now(name)
            finally:
                # So a test can wait for the queue to drain rather than sleep.
                self._queue.task_done()

    def _play_now(self, name: str) -> None:
        path = SOUNDS_DIR / f"{name}.wav"
        if not path.exists():
            return
        try:
            if self.player == [WINSOUND]:
                import winsound

                winsound.PlaySound(str(path), winsound.SND_FILENAME)
            else:
                assert self.player is not None
                subprocess.run(
                    [*self.player, str(path)],
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                    check=False,
                )
        except Exception:
            # A sound is never worth a crash. The player vanished, the audio
            # server went away, the platform said no -- the game goes quiet and
            # carries on, which is the same thing it does on a machine that
            # never had a player at all.
            self._muted = True
